[package]
name = "micro_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
micro_test_case = { path = "../micro_test_case" }

[features]
replace_assert = ["micro_test_case/replace_assert"]
